spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: keycloak
              uri: http://keycloak:8080
              predicates:
                - Path=/keycloak/**
                - RewritePath=/keycloak/(?<path>.*), /${path}
              filters:
                - StripPrefix=1

            - id: authentication-service
              uri: ${AUTH_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/**
                - RewritePath=/api/auth/(?<segment>.*), /${segment}
              filters:
                - StripPrefix=1