spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}
      enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: authentication-service
              uri: lb://authentication-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2