spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: keycloak
              uri: http://keycloak:8080
              predicates:
                - Path=/keycloak/**
              filters:
                - StripPrefix=1
                - RewritePath=/keycloak/(?<path>.*), /${path}
            - id: authentication-service
              uri: ${AUTH_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
                - RewritePath=/auth/(?<path>.*), /${path}