spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: authentication-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2